apiVersion: v2
name: pterodactyl-panel
description: Pterodactyl Panel Helm Chart

type: application

version: 0.2.0

appVersion: "1.11.11"

dependencies:
  - name: valkey
    version: 3.0.26
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: valkey.enabled
