apiVersion: v2
name: pterodactyl-panel
description: Pterodactyl Panel Helm Chart

type: application

version: 0.2.5

# renovate: image=ghcr.io/blueprintframework/blueprint
appVersion: v1.11.11

dependencies:
  - name: valkey
    version: 3.0.31
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: valkey.enabled
