replicas: 1

panel:
  debug: false
  telemetry: true
  url: "https://panel.example.com"
  trusted_proxies: "*"
  database:
    host: mariadb-primary
    port: 3306
    name: panel
    existingSecret:
      secretName: pterodactyl-panel-db
      usernameKey: username
      passwordKey: password

  appKey:
    existingSecret:
      secretName: pterodactyl-panel
      key: appKey

  redis:
    host: app-valkey-master
    port: 6379
    auth:
      enabled: true
      existingSecret:
        secretName: pterodactyl-panel
        passwordKey: redis-password

  cache_driver: file
  session_driver: file
  queue_connection: sync

persistence:
  appStorage:
    storageClass: null
    accessModes:
      - ReadWriteMany
    size: 4Gi
  varStorage:
    storageClass: null
    accessModes:
      - ReadWriteMany
    size: 4Gi
  app:
    storageClass: null
    accessModes:
      - ReadWriteMany
    size: 4Gi

# set to local if s3 is disabled
backups:
  s3:
    enabled: false
    bucket: ""
    region: ""
    endpoint: ""
    accessKeyId:
      existingSecret:
        secretName: pterodactyl-panel
        key: s3-access-key-id
    secretAccessKey:
      existingSecret:
        secretName: pterodactyl-panel
        key: s3-secret-access-key

    storageClass: null
    # 5GB
    maximumPartSize: "5368709120"
    # minutes
    presignedUrlExpiration: "60"


image:
  repository: ghcr.io/blueprintframework/blueprint
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:  {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 2000m
    memory: 1Gi
  requests:
    cpu: 50m
    memory: 150Mi

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

nodeSelector: {}

tolerations: []

affinity: {}

valkey:
  enabled: false
  architecture: standalone

additionalVolumes: []
  # - name: my-volume
  #   emptyDir: {}

additionalVolumeMounts: []
  # - name: my-volume
  #   mountPath: /path/in/container
