apiVersion: v2
name: paperless
description: A Helm chart for Paperless

type: application

version: 0.1.29

appVersion: "2.18.2"

dependencies:
  - name: valkey
    version: 3.0.31
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: valkey.enabled
