apiVersion: v2
name: paperless
description: A Helm chart for Paperless

type: application

version: 0.1.27

appVersion: "2.17.1"

dependencies:
  - name: valkey
    version: 3.0.26
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: valkey.enabled
