apiVersion: v2
name: paperless
description: A Helm chart for Paperless

type: application

version: 0.1.30

# renovate: image=ghcr.io/paperless-ngx/paperless-ngx
appVersion: 2.18.3

dependencies:
  - name: valkey
    version: 3.0.31
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: valkey.enabled
