apiVersion: v2
name: paperless
description: A Helm chart for Paperless

type: application

version: 0.1.19

appVersion: "2.16.3"

dependencies:
  - name: valkey
    version: 3.0.12
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: valkey.enabled
  - name: postgresql
    version: 16.7.11
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
