apiVersion: v2
name: paperless
description: A Helm chart for Paperless

type: application

version: 0.1.0

appVersion: "2.14.7"

dependencies:
  - name: valkey
    version: 2.4.7
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: valkey.enabled
  - name: postgresql
    version: 16.6.0
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
