apiVersion: v2
name: paperless
description: A Helm chart for Paperless

type: application

version: 0.1.24

appVersion: "2.17.1"

dependencies:
  - name: valkey
    version: 3.0.16
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: valkey.enabled
  - name: postgresql
    version: 16.7.15
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
