{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "paperless.fullname" . }}
  labels:
    {{- include "paperless.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "paperless.selectorLabels" . | nindent 6 }}
  policyTypes:
    {{- if .Values.networkPolicy.ingress.enabled }}
    - Ingress
    {{- end }}
    {{- if .Values.networkPolicy.egress.enabled }}
    - Egress
    {{- end }}

  {{- if .Values.networkPolicy.ingress.enabled }}

  {{- if .Values.networkPolicy.ingress.rules }}
  ingress: {{- toYaml .Values.networkPolicy.ingress.rules | nindent 2 }}
  {{- else }}
  ingress: []
  {{- end }}

  {{- end }}

  {{- if .Values.networkPolicy.egress.enabled }}
  {{- if .Values.networkPolicy.egress.rules }}
  egress: {{- toYaml .Values.networkPolicy.egress.rules | nindent 2 }}
  {{- else }}
  egress: []
  {{- end }}

  {{- end }}
{{- end}}
