name: Update Helm Chart Index

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4.3.0

      - name: Build dependencies for all charts
        run: |
          for chart in charts/*/; do
            if [ -d "$chart" ]; then
              echo "Building dependencies for $chart"
              helm dep update "$chart"  # Build dependencies for the chart
            fi
          done

      - name: Package all charts
        run: |
          for chart in charts/*/; do
            if [ -d "$chart" ]; then
              echo "Packaging $chart"
              helm package "$chart"  # Package the chart
            fi
          done

      - name: Update Helm chart index
        run: |
          helm repo index .

      - name: Commit updated index.yaml
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git branch -d charts || true
          git switch -c charts
          git add *.tgz
          git add index.yaml
          git commit -m "Update chart index and packaged charts"
          git push --force -u origin charts

